import "../Scss/globals.scss";

import Header from "./Header.jsx";

// head import section
// bootstrap connect
import "bootstrap/dist/css/bootstrap.min.css";

import { BootstrapClient } from "@/components/ClientComponent.jsx";

// context api
import { ContextProvider } from "@/components/ClientComponent.jsx";

export const metadata = {
  title: "Todo-App",
  description: "Generated by Arham ullah khan",
  icons: [{ rel: "icon", url: `/favicon`.src }],
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head></head>

      <body className="">
        <BootstrapClient />
        <ContextProvider>
          <Header />
          {children}
        </ContextProvider>
      </body>
    </html>
  );
}
